fix faccessat01.c build fails with security flags
When the distro is poky-lsb, fix the following error:

| In file included from ../../../../include/old/test.h:47:0,
|                  from faccessat01.c:44:
| faccessat01.c: In function 'setup':
| ../../../../include/old/old_safe_file_ops.h:55:27: error: format not a string literal and no format arguments [-Werror=format-security]
|                    (path), (fmt), ## __VA_ARGS__)
|                            ^
| faccessat01.c:132:2: note: in expansion of macro 'SAFE_FILE_PRINTF'
|   SAFE_FILE_PRINTF(cleanup, testfile, testfile);
|   ^~~~~~~~~~~~~~~~
| ../../../../include/old/old_safe_file_ops.h:55:27: error: format not a string literal and no format arguments [-Werror=format-security]
|                    (path), (fmt), ## __VA_ARGS__)
|                            ^
| faccessat01.c:133:2: note: in expansion of macro 'SAFE_FILE_PRINTF'
|   SAFE_FILE_PRINTF(cleanup, testfile2, testfile2);
|   ^~~~~~~~~~~~~~~~

This is because in macro "SAFE_FILE_PRINTF", its third argument should be a
format arguments, but in file faccessat01.c, it passed the same argument to
macro "SAFE_FILE_PRINTF", so it results in the fails. It should pass the format
string to the third argument.

The same for file fchmodat01.c.

Resolves: LTP-1
Signed-off-by: Anson <aouyang@sierrawireless.com>
Signed-off-by: Dengke Du <dengke.du@windriver.com>
Upstream-Status: Pending
Change-Id: I4f4d73b281b123982099d48a9ec9460b46898630