setregid01: Fix security warning for string formatting
GCC 8.2.0 complains with the following:
  setregid01.c: In function 'run':
  setregid01.c:47:3: error: format not a string literal and no format arguments [-Werror=format-security]
     tst_res(TFAIL | TTERRNO, tc->msg);
     ^~~~~~~
because there is no string formatting in the message. This can
be seen with CFLAGS set to:
  -Wformat -Wformat-security -Werror=format-security
as Yocto Project's Poky does, e.g.:
  http://errors.yoctoproject.org/Errors/Details/230043/

Upstream-Status: Backport [46e1eda55f188810e6bf3a939b92d604321807ae]

Signed-off-by: Daniel Díaz <daniel.diaz@linaro.org>
Reviewed-by: Enji Cooper <yaneurabeya@gmail.com>
Resolves: LTP-2
Signed-off-by: Anson Ouyang <aouyang@sierrawireless.com>
Change-Id: I0fa16a5c0c15f478444ab31268a1c490cf4acd07